model_selection:
    model:
      LinearRegression:
        search_param_grid:
          fit_intercept: [True]
          n_jobs: [-1]

      XGBRegressor:
        search_param_grid:
          n_estimators: 100
          learning_rate: 0.1
          max_depth: 3
          subsample: 0.8
          colsample_bytree: 0.8
          objective: reg:squarederror
        random_state: 42

      RandomForestRegressor:
        search_param_grid:
          n_estimators: 100
          max_depth: 10
          min_samples_split: 2
          min_samples_leaf: 1
          max_features: auto
          n_jobs: -1
          random_state: 42

      GradientBoostingRegressor:
        search_param_grid:
          n_estimators: 100
          learning_rate: 0.1
          max_depth: 3
          subsample: 1.0
          loss: squared_error
          random_state: 42
